<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MX.Caching</PackageId>
    <Description>Core MX caching composition package.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MX.Caching.Abstractions\MX.Caching.Abstractions.csproj" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
