<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MX.Caching.Abstractions</PackageId>
    <Description>Abstractions for MX caching packages.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
