<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MX.Caching.TableStorage</PackageId>
    <Description>Azure Table Storage integration package for MX caching.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="..\MX.Caching.Abstractions\MX.Caching.Abstractions.csproj" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MX.Caching.Tests" />
    <InternalsVisibleTo Include="MX.Caching.IntegrationTests" />
  </ItemGroup>
</Project>
