<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MX.Caching.TableStorage</PackageId>
    <Description>Azure Table Storage integration package for MX caching.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" />
    <ProjectReference Include="..\MX.Caching.Abstractions\MX.Caching.Abstractions.csproj" />
    <ProjectReference Include="..\MX.Caching\MX.Caching.csproj" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
